#!/usr/bin/env bash

CURRENT=$PWD
REPO=pmarelas288
IMAGES=$@

if [ -z "$IMAGES" ]; then
	IMAGES="loadgenerator loadgeneratorredis adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice"
fi

for SERVICE in $IMAGES
do
	echo "##### Building $SERVICE #####"
	cd $CURRENT
	cd src/$SERVICE
	docker build -t $REPO/$SERVICE .
	if [ $? -ne 0 ]; then
		echo "##### Failed to build $SERVICE #####"
		exit 1
	fi
	docker push $REPO/$SERVICE
done