#!/usr/bin/env bash

CURRENT=$PWD
REPO=pmarelas288
IMAGES=$1

if [ -z "$IMAGES" ]; then
	IMAGES="loadgenerator loadgeneratorredis adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice"
fi

for SERVICE in $IMAGES
do
	echo "##### Building $SERVICE #####"
	cd $CURRENT
	cd src/$SERVICE
	docker build -t $REPO/$SERVICE .
	docker push $REPO/$SERVICE
done