# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: checkoutservice
          image: pmarelas288/checkoutservice
          ports:
          - containerPort: 5050
          env:
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-key
                key: new-relic-license-key
          - name: NEW_RELIC_APP_NAME
            value: "store-checkoutservice"
          - name: NEW_RELIC_LOG
            value: "stdout"
          - name: NEW_RELIC_LOG_LEVEL
            value: "info"
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          startupProbe:
            failureThreshold: 30
            periodSeconds: 30
            timeoutSeconds: 10
            grpc:
              port: 5050
          readinessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            grpc:
              port: 5050
          livenessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            grpc:
              port: 5050            
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 20m
              memory: 75Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
